[workspace]
members = ["environment","repo","src"]
resolver = "3"

# [package]
# name = "src"
# version = "0.1.0"
# edition = "2024"

# [dependencies]
# assert_cmd = "2.0.17"
# clap = { version = "4.5.43", features = ["derive"] }
