[package]
name = "repo"
version = "0.1.0"
edition = "2024"

[dependencies]
derivative = "2.2.0"
dirs = "6.0.0"
git-url-parse = "0.6.0"
git2 = "0.20.3"
rust-fuzzy-search = "0.1.1"
shellexpand = "3.1.1"
thiserror = "2.0.17"
walkdir = "2.5.0"
