[[language]]
name = "just"
auto-format = true

[language.formatter]
command = "just"
args = ["--justfile", "/dev/stdin", "--dump"]

[[language]]
name = "markdown"
auto-format = true

[language.formatter]
command = "prettierd"
args = [".md"]

[[language]]
name = "nix"
auto-format = true

[language.formatter]
command = "alejandra"

[[language]]
name = "toml"
auto-format = true

[language.formatter]
command = "taplo"
args = ["format", "-"]
